### ISSUE TITLE
Wavelength calculation uses deep water approximation

### ISSUE THREAD

**Issue by conlin-matt** [chrisleaman/py-wave-runup#158]
Hey Chris-

I've been playing around with this package, which is super awesome that you put together by the way. Super nice to have all of these models in one easy-to-access place! I was testing your Stockdon model vs. my personal implementation, and noticed that, when period is passed to the Stockdon class without a wavelength, your code [uses the deep water approximation to calculate wavelength](https://github.com/chrisleaman/py-wave-runup/blob/c9cb3d9e86ea77a68b709d9b1964b8ef7e4d8152/py_wave_runup/models.py#L58). As shown in the attached figure for the FRF 17 m buoy, this can lead to substantial (50 cm in this specific case) R2 differences relative to using the full general LWT wavelength expression, especially for the largest values (deep water assumption violated). To me, it seems like it would be more robust to require the user to provide a measurement depth if a period is passed without a wavelength in order to use the full expression to calculate the wavelength. I'm happy to do a PR for this, if you want. What do you think?

![py_wave_runup](https://user-images.githubusercontent.com/32144021/124275480-958df400-db10-11eb-8268-26d2e8ab3975.png)

**Comment by chrisleaman** [comment]
Hey Matt! Thanks for the suggestion, this is a really good point!

A PR would be really appreciated if you're able to. My thoughts on the implementation would be to add a `depth` argument to the RunupModel class. If `depth` isn't specified then just assume deep water conditions.

If you're happy to update the class, I can handle the documentation/tests/examples etc if you want. It's been a while since I looked at this, so it'll be a good chance to add a few more models and make sure everything is still working :)
